/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DeliveryStatus = { 'assigned' : null } |
  { 'delivering' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'completed' : null } |
  { 'quoted' : null };
export interface DriverApplication {
  'id' : bigint,
  'applicantPrincipal' : Principal,
  'message' : string,
  'timestamp' : bigint,
}
export interface DriverProfile {
  'principal' : Principal,
  'profile' : [] | [UserProfile],
}
export interface Message {
  'id' : bigint,
  'text' : string,
  'orderId' : bigint,
  'imageKey' : [] | [string],
  'timestamp' : bigint,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : DeliveryStatus,
  'contactInfo' : string,
  'customerPrincipal' : [] | [Principal],
  'description' : string,
  'address' : string,
  'quotedPrice' : [] | [bigint],
  'driverPrincipal' : [] | [Principal],
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdminIfFirst' : ActorMethod<[], boolean>,
  'claimOrder' : ActorMethod<[bigint], undefined>,
  'completeOrder' : ActorMethod<[bigint], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'demoteDriver' : ActorMethod<[Principal], undefined>,
  'getAdminDriverMessages' : ActorMethod<[Principal], Array<Message>>,
  'getAllDrivers' : ActorMethod<[], Array<Principal>>,
  'getAllDriversWithProfiles' : ActorMethod<[], Array<DriverProfile>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAvailableOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerOrders' : ActorMethod<[], Array<Order>>,
  'getDriverApplications' : ActorMethod<[], Array<DriverApplication>>,
  'getDriverMessages' : ActorMethod<[bigint], Array<Message>>,
  'getMyDriverOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderMessages' : ActorMethod<[bigint], Array<Message>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerDriver' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markOrderPaid' : ActorMethod<[bigint], undefined>,
  'promoteToDriver' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendAdminDriverMessage' : ActorMethod<[Principal, string], undefined>,
  'sendDriverMessage' : ActorMethod<[bigint, string, [] | [string]], undefined>,
  'sendDriverToAdminMessage' : ActorMethod<[string], undefined>,
  'sendOrderMessage' : ActorMethod<[bigint, string, [] | [string]], undefined>,
  'setOrderPrice' : ActorMethod<[bigint, bigint], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'startDelivery' : ActorMethod<[bigint], undefined>,
  'submitDeliveryRequest' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'submitDriverApplication' : ActorMethod<[string], bigint>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];